import { useEffect, useState } from 'react'
import { Grid, Text, Title, Container, Space } from '@mantine/core'
import Head from 'next/head'
import Image from 'next/image'
import RecipeCard from '../components/recipes/RecipeCard/RecipeCard'
import styles from '../styles/Home.module.css'

export default function Home() {

  const [randomRecipes, setRandomRecipes] = useState([])

  useEffect(() => {
    console.log(process.env.NEXT_PUBLIC_SPOONACULAR_API_SECRET_KEY)
    getRandomRecipes()
  }, []) 

  const getRandomRecipes = async () => {
    const api = await fetch(`https://api.spoonacular.com/recipes/random?apiKey=${process.env.NEXT_PUBLIC_SPOONACULAR_API_SECRET_KEY}&number=9`)
    const data = await api.json()
    console.log(data)
    setRandomRecipes(data.recipes)
  }
  
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        
        <Container fluid>
        <Title order={2}>Try out new recipes</Title>
        <Space h="xl" />
        <Grid>
          {randomRecipes.map(recipe => (
            <Grid.Col md={6} lg={4} key={recipe.id}>
              <RecipeCard 
                id={recipe.id}
                title={recipe.title}
                image={recipe.image}
                readyInMinutes={recipe.readyInMinutes}
                servings={recipe.servings}
                
              />
            </Grid.Col>
          ))}
        </Grid>
        </Container>
      </main>
    </div>
  )
}
